[package]
name = "challenge_12"
version = "0.1.0"
authors = ["Josh Morrow <josh@jcmorrow.com>"]
edition = "2018"

[dependencies]
challenge_10 = { path = "../challenge_10" }
challenge_11 = { path = "../challenge_11" }
lazy_static = "1.2.0"
