[package]
name = "challenge_12"
version = "0.1.0"
authors = ["Josh Morrow <josh@jcmorrow.com>"]
edition = "2018"

[dependencies]
challenge_2 = { path = "../challenge_2" }
challenge_3 = { path = "../challenge_3" }